### ISSUE TITLE
 Internal PortAudio error on MacOS

### ISSUE THREAD

**Issue by othrif** [oliverguhr/wav2vec2-live#1] opened 2021-04-21 17:01 UTC
Thanks for sharing this project! 

I am on a mac, and I seem to have problems with opening the pyAudio stream here: https://github.com/oliverguhr/wav2vec2-live/blob/main/live_asr.py#L59-L64

Looking at the documentation: https://people.csail.mit.edu/hubert/pyaudio/docs/ I see that to use a microphone, a callback function is required. 

I made sure that I am picking the correct device microphone here: https://github.com/oliverguhr/wav2vec2-live/blob/main/live_asr.py#L56-L57

The error I am getting is:
``` bash 
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/othrif/spectrum/voice/experiment/wav2vec/042121/wav2vec2-live/live_asr.py", line 62, in vad_process
    stream = audio.open(input_device_index=selected_input_device_id,
  File "/Users/othrif/spectrum/voice/experiment/wav2vec/042121/wav2vec2-live/.venv/lib/python3.9/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/Users/othrif/spectrum/voice/experiment/wav2vec/042121/wav2vec2-live/.venv/lib/python3.9/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9986] Internal PortAudio error
```

Any thoughts on what might be causing this?

**Comment by oliverguhr** [comment] 2021-04-22 10:31
Thanks for the feedback! Unfortunately, I do not own a mac to reproduce this issue 😔. 
Pyaudio is wrapper for the portaudio lib. You need to have port audio installed on your mac in order to make this work. 
This blog post might help you: [Installing PyAudio on MacOs](https://medium.com/@wagnernoise/installing-pyaudio-on-macos-9a5557176c4d)

**Comment by othrif** [comment] 2021-04-22 13:40
Thanks @oliverguhr for the reply!

So I fixed the Pyaudio issue, but I came across another issue, I am not getting any audio through despite double checking my device and that I am getting the audio stream using pyaudio in some test code.

Upon inspection, it seems these variables `LiveWav2Vec2.is_listening.get()` in https://github.com/oliverguhr/wav2vec2-live/blob/main/live_asr.py#L67 and https://github.com/oliverguhr/wav2vec2-live/blob/main/live_asr.py#L84 keep a `None` value. They do not get updated with https://github.com/oliverguhr/wav2vec2-live/blob/main/live_asr.py#L31 for whatever reason.

What's the role of https://github.com/oliverguhr/wav2vec2-live/blob/main/live_asr.py#L13? Why not just use https://github.com/oliverguhr/wav2vec2-live/blob/main/live_asr.py#L18?

**Comment by oliverguhr** [comment] 2021-04-22 14:37
I need a way to tell the ASR and VAD thread that the main program closes. My first attempt was to use L18, a class property to signal that both threads should end. But this is not working since these threads do not have access to the class properties. So I needed a shared, thread-safe variable for this which is the ContextVar in L18. 

Long story short - L18 is not used and obsolete.  

However, that this lines ```LiveWav2Vec2.is_listening.set(True)``` fails is very strange. Since the ContextVars module is a python build-in feature and should just work.

Which python version are you using?

**Comment by othrif** [comment] 2021-04-22 14:40
Your explanation makes sense! 

I am using Python 3.8.5. Indeed the problem is that `LiveWav2Vec2.is_listening.set(True)` do not overwrite the values inside ` vad_process()` and `asr_process()`. 

Will be happy to test out things if you have suggetions.

Thanks!

**Comment by oliverguhr** [comment] 2021-04-22 14:49
Very strange - I am running the same python version - and it works just fine. We could do an online meeting and look at this together.

**Comment by arossbach10** [comment] 2021-04-22 14:49
Hi,

I see the same behavior on Python 3.6.12 on Windows.
As a quick workaround, I removed the sync and the program runs.

**Comment by othrif** [comment] 2021-04-22 14:57
@oliverguhr, yes i will be happy to jump in a quick call. What's the best way to do that?

@arossbach10, could you clarify what you mean by removing the sync?

**Comment by arossbach10** [comment] 2021-04-22 14:59
I set it to true before each get()

        LiveWav2Vec2.is_listening.set(True) 
        while LiveWav2Vec2.is_listening.get():
             ...

**Comment by arossbach10** [comment] 2021-04-22 15:14
It is not a nice solution and in some cases, I would expect synchronization is required.
But I have not worked with contextvars.

**Comment by oliverguhr** [comment] 2021-04-22 15:15
@arossbach10 Thank you for the hint! This would prevent the threads from being closed if by the ```stop``` function, but it does not matter if you close the program anyway. Really funny is, that my ContextVar implementation does not work either. I need to investigate this.

**Comment by arossbach10** [comment] 2021-04-22 15:21
@oliverguhr  But it could also go wrong at the start.  I would also be interested to know why the ContextVar is not working.

**Comment by oliverguhr** [comment] 2021-04-22 15:41
If I set the ContextVar to False it will remain True for the other threads. I must have overlooked something. However this [blog post](https://blog.miguelgrinberg.com/post/how-to-kill-a-python-thread) recommends using ```threading.Event()``` send the signal.

**Comment by oliverguhr** [comment] 2021-04-23 10:14
@arossbach10 @othrif I removed the Contextvar code and added some code to gracefully close the threads. *It works on my machine :)* I would be happy if you could check that and provide some feedback.

**Comment by oliverguhr** [comment] 2021-05-04 13:12
@othrif I don't know, this could be a Mac-specific port audio issue. Debugging it on a Mac would be helpful.

**Comment by oliverguhr** [comment] 2021-07-05 16:04
@othrif Since I don't down a mac, I can not solve this issue. I close this ticket, if you fix it - feel free to reopen it.

**Closed by oliverguhr** 2021-07-05 16:04 UTC
